### ISSUE TITLE
Passing a string for the 2nd param doesn't work

### ISSUE THREAD

**Issue by billiegoose** [ratlog/ratlog.js#7]
Hi there! I'm just trying this library out for the first time, and made a simple mistake:

```js
const log = require('ratlog')(process.stdout)
log('hello...', 'tag')
```

Imagine my surprise! when it printed this:
```
hello... | 0: t | 1: a | 2: g
```

Since sometimes logging statements don't run except in edge cases, (e.g. inside a try/catch to handle a network error) a mistake like this might not be caught during development. Would you consider dynamically checking the type of the second argument? If it's an object, treat it as fields, and if it's a string, treat it as a tag?

**Comment by jorinvo** [comment]
@wmhilton hi, good point! I will definitely add this!

As a quick note, for now, if you only want a tag, I recommend doing this:

```js
log.tag('tag')('hello...')
```

**Comment by jorinvo** [comment]
@wmhilton version `0.2.0` is out. You can give it a try and let me know if we can close the issue :)

**Comment by billiegoose** [comment]
Works great!!! Awesome sauce!
